dist: trusty
sudo: false
language: cpp
compiler: clang

install:
  - curl -sSf https://sh.rustup.rs | sh -s -- -y --verbose
  - PATH=$PATH:$HOME/.cargo/bin
  - rustup target add x86_64-unknown-linux-musl

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.rustup
    - $TRAVIS_BUILD_DIR/target

script: cargo build --verbose --target x86_64-unknown-linux-musl
