[package]
name = "wdsapi"
version = "0.1.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]

# The following dependencies are all 0.x versions.
# 0.x means they make no promises, so we just grab the latest.
[dependencies.chrono]
version = "*"
features = ["serde"]

[dependencies.hyper]
version = "*"
default-features = false

[dependencies]
hyper-rustls = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
