[package]
name = "wdsapi"
version = "1.0.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]

[dependencies.chrono]
version = "0.2"
features = ["serde"]

[dependencies.hyper-rustls]
git = "https://github.com/bruceadams/hyper-rustls.git"

[dependencies]
hyper = "0.10"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
