[package]
name = "wdsapi"
version = "1.0.0"
authors = ["Bruce Adams <bruce.adams@acm.org>"]

[dependencies.chrono]
version = "0.2"
features = ["serde"]

[dependencies]
hyper = "0.10"
hyper-rustls = "0.3"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
